// <auto-generated />
using System;
using CafeteriaKwai.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CafeteriaKwai.Migrations
{
    [DbContext(typeof(CafeContext))]
    partial class CafeContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CafeComSeuTioAdmin.Data.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageFile")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageFileName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ShortDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Savory",
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ut, tenetur natus doloremque laborum quos iste ipsum rerum obcaecati impedit odit illo dolorum ab tempora nihil dicta earum fugiat. Temporibus, voluptatibus. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ut, tenetur natus doloremque laborum quos iste ipsum rerum obcaecati impedit odit illo dolorum ab tempora nihil dicta earum fugiat. Temporibus, voluptatibus.",
                            ImageFileName = "charcuterie.png",
                            Name = "Charcuterie",
                            Price = 4m,
                            ShortDescription = "For indecisive food afficianados."
                        },
                        new
                        {
                            Id = 2,
                            Category = "Dessert",
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ut, tenetur natus doloremque laborum quos iste ipsum rerum obcaecati impedit odit illo dolorum ab tempora nihil dicta earum fugiat. Temporibus, voluptatibus. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ut, tenetur natus doloremque laborum quos iste ipsum rerum obcaecati impedit odit illo dolorum ab tempora nihil dicta earum fugiat. Temporibus, voluptatibus.",
                            ImageFileName = "waffles.png",
                            Name = "Waffles",
                            Price = 4m,
                            ShortDescription = "They need no introduction."
                        },
                        new
                        {
                            Id = 3,
                            Category = "Savory",
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ut, tenetur natus doloremque laborum quos iste ipsum rerum obcaecati impedit odit illo dolorum ab tempora nihil dicta earum fugiat. Temporibus, voluptatibus. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ut, tenetur natus doloremque laborum quos iste ipsum rerum obcaecati impedit odit illo dolorum ab tempora nihil dicta earum fugiat. Temporibus, voluptatibus.",
                            ImageFileName = "salad-special.png",
                            Name = "Santa Fe Salad",
                            Price = 4m,
                            ShortDescription = "Our house special - we love it."
                        },
                        new
                        {
                            Id = 4,
                            Category = "Savory",
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ut, tenetur natus doloremque laborum quos iste ipsum rerum obcaecati impedit odit illo dolorum ab tempora nihil dicta earum fugiat. Temporibus, voluptatibus. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ut, tenetur natus doloremque laborum quos iste ipsum rerum obcaecati impedit odit illo dolorum ab tempora nihil dicta earum fugiat. Temporibus, voluptatibus.",
                            ImageFileName = "salad-house.png",
                            Name = "Caesar Salad",
                            Price = 4m,
                            ShortDescription = "Classically, delicious fresh."
                        },
                        new
                        {
                            Id = 5,
                            Category = "Savory",
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ut, tenetur natus doloremque laborum quos iste ipsum rerum obcaecati impedit odit illo dolorum ab tempora nihil dicta earum fugiat. Temporibus, voluptatibus. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ut, tenetur natus doloremque laborum quos iste ipsum rerum obcaecati impedit odit illo dolorum ab tempora nihil dicta earum fugiat. Temporibus, voluptatibus.",
                            ImageFileName = "noodles.png",
                            Name = "Noodles",
                            Price = 4m,
                            ShortDescription = "Delicious carbs on the go."
                        },
                        new
                        {
                            Id = 6,
                            Category = "Dessert",
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ut, tenetur natus doloremque laborum quos iste ipsum rerum obcaecati impedit odit illo dolorum ab tempora nihil dicta earum fugiat. Temporibus, voluptatibus. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ut, tenetur natus doloremque laborum quos iste ipsum rerum obcaecati impedit odit illo dolorum ab tempora nihil dicta earum fugiat. Temporibus, voluptatibus.",
                            ImageFileName = "cake.png",
                            Name = "Red Velvet Cake",
                            Price = 4m,
                            ShortDescription = "Red Velvet...for those who prefer finer things."
                        },
                        new
                        {
                            Id = 7,
                            Category = "Dessert",
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ut, tenetur natus doloremque laborum quos iste ipsum rerum obcaecati impedit odit illo dolorum ab tempora nihil dicta earum fugiat. Temporibus, voluptatibus. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ut, tenetur natus doloremque laborum quos iste ipsum rerum obcaecati impedit odit illo dolorum ab tempora nihil dicta earum fugiat. Temporibus, voluptatibus.",
                            ImageFileName = "cupcake.png",
                            Name = "Cupcake",
                            Price = 4m,
                            ShortDescription = "Vanilla cupcakes with the perfect level of sweetness."
                        },
                        new
                        {
                            Id = 8,
                            Category = "Dessert",
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ut, tenetur natus doloremque laborum quos iste ipsum rerum obcaecati impedit odit illo dolorum ab tempora nihil dicta earum fugiat. Temporibus, voluptatibus. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ut, tenetur natus doloremque laborum quos iste ipsum rerum obcaecati impedit odit illo dolorum ab tempora nihil dicta earum fugiat. Temporibus, voluptatibus.",
                            ImageFileName = "muffin.png",
                            Name = "Muffin",
                            Price = 3m,
                            ShortDescription = "The perfect way to start a Monday morning."
                        },
                        new
                        {
                            Id = 9,
                            Category = "Kit",
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ut, tenetur natus doloremque laborum quos iste ipsum rerum obcaecati impedit odit illo dolorum ab tempora nihil dicta earum fugiat. Temporibus, voluptatibus. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ut, tenetur natus doloremque laborum quos iste ipsum rerum obcaecati impedit odit illo dolorum ab tempora nihil dicta earum fugiat. Temporibus, voluptatibus.",
                            ImageFileName = "chocolate.png",
                            Name = "Chocolate Bites",
                            Price = 5m,
                            ShortDescription = "Rich and sweet chocolate bites for those in need of a special treat."
                        },
                        new
                        {
                            Id = 10,
                            Category = "Dessert",
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ut, tenetur natus doloremque laborum quos iste ipsum rerum obcaecati impedit odit illo dolorum ab tempora nihil dicta earum fugiat. Temporibus, voluptatibus. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ut, tenetur natus doloremque laborum quos iste ipsum rerum obcaecati impedit odit illo dolorum ab tempora nihil dicta earum fugiat. Temporibus, voluptatibus.",
                            ImageFileName = "pumpkinbread.png",
                            Name = "Frosted Pumpkin Bread",
                            Price = 4m,
                            ShortDescription = "A seasonal delight we offer every autumn."
                        },
                        new
                        {
                            Id = 11,
                            Category = "Kit",
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ut, tenetur natus doloremque laborum quos iste ipsum rerum obcaecati impedit odit illo dolorum ab tempora nihil dicta earum fugiat. Temporibus, voluptatibus. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ut, tenetur natus doloremque laborum quos iste ipsum rerum obcaecati impedit odit illo dolorum ab tempora nihil dicta earum fugiat. Temporibus, voluptatibus.",
                            ImageFileName = "granola.png",
                            Name = "Granola with Nuts",
                            Price = 3m,
                            ShortDescription = "It's not flashy, but it sure is healthy."
                        },
                        new
                        {
                            Id = 12,
                            Category = "Kit",
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ut, tenetur natus doloremque laborum quos iste ipsum rerum obcaecati impedit odit illo dolorum ab tempora nihil dicta earum fugiat. Temporibus, voluptatibus. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ut, tenetur natus doloremque laborum quos iste ipsum rerum obcaecati impedit odit illo dolorum ab tempora nihil dicta earum fugiat. Temporibus, voluptatibus.",
                            ImageFileName = "cookies.png",
                            Name = "Chocolate Chip Cookies",
                            Price = 2m,
                            ShortDescription = "They're made fresh every day, and they taste like it."
                        },
                        new
                        {
                            Id = 13,
                            Category = "Dessert",
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ut, tenetur natus doloremque laborum quos iste ipsum rerum obcaecati impedit odit illo dolorum ab tempora nihil dicta earum fugiat. Temporibus, voluptatibus. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ut, tenetur natus doloremque laborum quos iste ipsum rerum obcaecati impedit odit illo dolorum ab tempora nihil dicta earum fugiat. Temporibus, voluptatibus.",
                            ImageFileName = "bagel.png",
                            Name = "Fresh Bagels",
                            Price = 5m,
                            ShortDescription = "They're just as round as donuts, but far more healthy!"
                        },
                        new
                        {
                            Id = 14,
                            Category = "Drink",
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ut, tenetur natus doloremque laborum quos iste ipsum rerum obcaecati impedit odit illo dolorum ab tempora nihil dicta earum fugiat. Temporibus, voluptatibus. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ut, tenetur natus doloremque laborum quos iste ipsum rerum obcaecati impedit odit illo dolorum ab tempora nihil dicta earum fugiat. Temporibus, voluptatibus.",
                            ImageFileName = "ground.png",
                            Name = "Dark Brewed Coffee",
                            Price = 2m,
                            ShortDescription = "A classic, refreshing original."
                        },
                        new
                        {
                            Id = 15,
                            Category = "Drink",
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ut, tenetur natus doloremque laborum quos iste ipsum rerum obcaecati impedit odit illo dolorum ab tempora nihil dicta earum fugiat. Temporibus, voluptatibus. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ut, tenetur natus doloremque laborum quos iste ipsum rerum obcaecati impedit odit illo dolorum ab tempora nihil dicta earum fugiat. Temporibus, voluptatibus.",
                            ImageFileName = "cappucino.png",
                            Name = "Latte",
                            Price = 3m,
                            ShortDescription = "More than just coffee, but still just coffee."
                        },
                        new
                        {
                            Id = 16,
                            Category = "Drink",
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ut, tenetur natus doloremque laborum quos iste ipsum rerum obcaecati impedit odit illo dolorum ab tempora nihil dicta earum fugiat. Temporibus, voluptatibus. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ut, tenetur natus doloremque laborum quos iste ipsum rerum obcaecati impedit odit illo dolorum ab tempora nihil dicta earum fugiat. Temporibus, voluptatibus.",
                            ImageFileName = "beans.png",
                            Name = "Americano",
                            Price = 3.5m,
                            ShortDescription = "Still classic, but a little more sophisticated."
                        },
                        new
                        {
                            Id = 17,
                            Category = "Drink",
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ut, tenetur natus doloremque laborum quos iste ipsum rerum obcaecati impedit odit illo dolorum ab tempora nihil dicta earum fugiat. Temporibus, voluptatibus. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ut, tenetur natus doloremque laborum quos iste ipsum rerum obcaecati impedit odit illo dolorum ab tempora nihil dicta earum fugiat. Temporibus, voluptatibus.",
                            ImageFileName = "design.png",
                            Name = "Designer Espresso",
                            Price = 6.5m,
                            ShortDescription = "Caffine has never looked so stunning."
                        },
                        new
                        {
                            Id = 18,
                            Category = "Drink",
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ut, tenetur natus doloremque laborum quos iste ipsum rerum obcaecati impedit odit illo dolorum ab tempora nihil dicta earum fugiat. Temporibus, voluptatibus. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ut, tenetur natus doloremque laborum quos iste ipsum rerum obcaecati impedit odit illo dolorum ab tempora nihil dicta earum fugiat. Temporibus, voluptatibus.",
                            ImageFileName = "cup.png",
                            Name = "Cappucino",
                            Price = 4.5m,
                            ShortDescription = "Rich and foamy comfort coffee."
                        },
                        new
                        {
                            Id = 19,
                            Category = "Drink",
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Description = "Uma deliciosa combinação de café gelado com calda de chocolate e leite cremoso. Perfeita para os dias quentes.",
                            ImageFileName = "icedmocha.png",
                            Name = "Iced Mocha",
                            Price = 5.5m,
                            ShortDescription = "Cold, creamy, and rich with chocolate."
                        },
                        new
                        {
                            Id = 20,
                            Category = "Drink",
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Description = "Smoothie de morango natural com iogurte grego, sem adição de açúcares artificiais. Ideal para qualquer hora do dia.",
                            ImageFileName = "smoothie.png",
                            Name = "Strawberry Smoothie",
                            Price = 6m,
                            ShortDescription = "Fresh strawberries blended to perfection."
                        },
                        new
                        {
                            Id = 21,
                            Category = "Drink",
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Description = "Chá verde gelado com infusão de manga e leve toque cítrico. Refrescante e saudável.",
                            ImageFileName = "mango-tea.png",
                            Name = "Mango Green Tea",
                            Price = 4m,
                            ShortDescription = "A tropical twist to classic green tea."
                        },
                        new
                        {
                            Id = 22,
                            Category = "Dessert",
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Description = "Camadas de biscoito champagne embebidas em café, com creme de mascarpone e cacau. Um clássico irresistível.",
                            ImageFileName = "tiramisu.png",
                            Name = "Tiramisu Cup",
                            Price = 6.5m,
                            ShortDescription = "A mini Italian classic."
                        },
                        new
                        {
                            Id = 23,
                            Category = "Dessert",
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Description = "Tartelete com base crocante, creme de baunilha e frutas frescas da estação.",
                            ImageFileName = "fruit-tart.png",
                            Name = "Fruit Tart",
                            Price = 5.5m,
                            ShortDescription = "Colorful, fresh and creamy."
                        },
                        new
                        {
                            Id = 24,
                            Category = "Dessert",
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Description = "Caixa com 6 macarons artesanais, nos sabores: pistache, chocolate, framboesa, limão, café e baunilha.",
                            ImageFileName = "macarons.png",
                            Name = "Macarons Box",
                            Price = 7m,
                            ShortDescription = "Assorted flavors, always elegant."
                        },
                        new
                        {
                            Id = 25,
                            Category = "Savory",
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Description = "Mini quiches de alho-poró, queijo e espinafre. Crocantes por fora, cremosas por dentro.",
                            ImageFileName = "quiche.png",
                            Name = "Mini Quiche",
                            Price = 3.5m,
                            ShortDescription = "Savory bites filled with love."
                        },
                        new
                        {
                            Id = 26,
                            Category = "Savory",
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Description = "Empanadas artesanais recheadas com espinafre refogado e queijo cremoso.",
                            ImageFileName = "empanada.png",
                            Name = "Spinach & Cheese Empanadas",
                            Price = 4m,
                            ShortDescription = "Golden crust and savory filling."
                        },
                        new
                        {
                            Id = 27,
                            Category = "Savory",
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Description = "Sanduíche com frango grelhado, molho pesto e tomate seco no pão rústico.",
                            ImageFileName = "pesto-sandwich.png",
                            Name = "Chicken Pesto Sandwich",
                            Price = 6m,
                            ShortDescription = "Grilled chicken with fresh pesto."
                        },
                        new
                        {
                            Id = 28,
                            Category = "Kit",
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Description = "Kit com pacote de café moído premium, xícara personalizada e biscoitos amanteigados.",
                            ImageFileName = "coffee-kit.png",
                            Name = "Café Lovers Kit",
                            Price = 25m,
                            ShortDescription = "Everything a coffee lover needs."
                        },
                        new
                        {
                            Id = 29,
                            Category = "Kit",
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Description = "Inclui mini quiche, suco natural, fatia de bolo caseiro e uma fruta fresca. Ideal para levar.",
                            ImageFileName = "brunch-pack.png",
                            Name = "Brunch Pack",
                            Price = 18m,
                            ShortDescription = "Perfect combo for late mornings."
                        },
                        new
                        {
                            Id = 30,
                            Category = "Kit",
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Description = "Uma caixa com mini versões de nossos principais doces: cupcake, brownie, cookie e fatia de bolo.",
                            ImageFileName = "dessert-kit.png",
                            Name = "Dessert Sampler Box-Egg",
                            Price = 20m,
                            ShortDescription = "A taste of our sweetest selections."
                        },
                        new
                        {
                            Id = 31,
                            Category = "Savory",
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Description = "Sanduíche artesanal com tomate fresco, mussarela de búfala e folhas de manjericão, regado com azeite extra virgem e servido em pão ciabatta.",
                            ImageFileName = "sandwich.png",
                            Name = "X-Sandwich",
                            Price = 5.5m,
                            ShortDescription = "Fresh, cheesy, and packed with flavor."
                        });
                });

            modelBuilder.Entity("CafeteriaKwai.Data.Models.City", b =>
                {
                    b.Property<int>("CityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CityId"));

                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CityId");

                    b.HasIndex("CountryId");

                    b.ToTable("Cities");
                });

            modelBuilder.Entity("CafeteriaKwai.Data.Models.Country", b =>
                {
                    b.Property<int>("CountryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CountryId"));

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CountryId");

                    b.ToTable("Countries");
                });

            modelBuilder.Entity("CafeteriaKwai.Data.Models.ProductDetail", b =>
                {
                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<bool>("IsLimitedEdition")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LaunchDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("TechnicalSpecs")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProductId");

                    b.ToTable("ProductDetails");
                });

            modelBuilder.Entity("CafeteriaKwai.Data.Models.City", b =>
                {
                    b.HasOne("CafeteriaKwai.Data.Models.Country", "Country")
                        .WithMany("Cities")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("CafeteriaKwai.Data.Models.ProductDetail", b =>
                {
                    b.HasOne("CafeComSeuTioAdmin.Data.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("CafeteriaKwai.Data.Models.Country", b =>
                {
                    b.Navigation("Cities");
                });
#pragma warning restore 612, 618
        }
    }
}
